# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  # For local vagrant development, comment line below when creating the image
  # then uncomment for doing `vagrant ssh` or do `su ubuntu`
  config.ssh.username = "ubuntu"
  # If you want more security, can put here the path to the key.
  # But also have to set the ipythonnb/init.sls state
  config.ssh.private_key_path = '/Users/danielfrg/.ssh/oculus/daniel_keypair.pem'

  Vagrant.configure("2") do |config|
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # For salt masterless, mount your file roots file root
  config.vm.synced_folder "salt/roots", "/srv"

  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
    salt.verbose = true
  end

  # AWS Provider
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = "my_aws"

    aws.security_groups = ["default"]
    aws.instance_type = "m1.large"
    aws.availability_zone = "us-east-1a"
    aws.ami = "ami-a73264ce"  # Precise 12.04 64 bits

    override.vm.box = "dummy"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/my_aws.pem"
  end

end
